spring:
  application:
    name: migration-service
  config:
    import:
      - optional:nacos:english-learning-common.yaml?group=${NACOS_CONFIG_GROUP:DEFAULT_GROUP}
      - optional:nacos:migration-service.yaml?group=${NACOS_CONFIG_GROUP:DEFAULT_GROUP}
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        group: ${NACOS_CONFIG_GROUP:DEFAULT_GROUP}
        file-extension: yaml
  main:
    web-application-type: none
